project:
  type: website
  render:
    - "*.qmd"
    - "!24_TOSCA_Nice"


website:
  title: "talks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



