project:
  type: website
  render:
    - "*.qmd"
    - "25_*/*.qmd"
    - "26_Moriond_UNIONS/*.qmd"
    - "!sasha_talks/"

website:
  title: "Talks"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


